-- =====================================================================
-- DEPRECATED — see supabase/setup.sql
--
-- This file used to create lowercase snake_case tables (students,
-- is_super_admin, …) that the app cannot query: Prisma generates quoted
-- PascalCase identifiers ("Student", "isSuperAdmin"), so anything built
-- from this file made every request fail with
--   ERROR 42703: column "is_super_admin" of relation "students" does not exist
-- (or "relation Student does not exist").
--
-- supabase/setup.sql is now the ONE canonical script: it creates the
-- exact Prisma schema (PascalCase), self-heals missing columns on older
-- databases (including the Semester 1/2 SGPA columns), drops these
-- legacy lowercase leftovers, and seeds the coordinator accounts.
--
-- Run supabase/setup.sql in the Supabase SQL Editor instead — it is
-- idempotent and safe to re-run.
-- =====================================================================
